'use strict';
const API='/dashboard/api/v1', $=id=>document.getElementById(id);
let data=null, view='overview', filter='', fetching=false;
const e=value=>String(value??'Unknown').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=value=>String(value??'unknown').replaceAll('_',' ');
const short=value=>value?String(value).slice(0,12)+'…':'Unknown';
const localTimezone=Intl.DateTimeFormat().resolvedOptions().timeZone;
const date=value=>{if(value==null||value==='')return 'Unknown';const d=new Date(typeof value==='number'?value*1000:value);return Number.isNaN(d.getTime())?'Unknown':d.toLocaleString(undefined,{timeZone:localTimezone,timeZoneName:'short'});};
const bytes=value=>value==null?'Unknown':value>=1073741824?(value/1073741824).toFixed(1)+' GiB':Math.round(value/1048576)+' MiB';
function badge(value){const good=['healthy','connected','responsive','completed','succeeded','done','present','available'];const bad=['unhealthy','unresponsive','failed','error','missing'];const warn=['stale','starting','disconnected','unavailable','pending'];return `<span class="badge ${good.includes(value)?'good':bad.includes(value)?'bad':warn.includes(value)?'warn':''}">${e(label(value))}</span>`;}
function gatewayState(a){if(a.container.status!=='running')return a.container.status;if(a.gateway.responsive===false)return 'unresponsive';if(a.gateway.stale)return 'stale';if(a.gateway.responsive===true)return 'responsive';return 'unknown';}
function details(type,id,name){return `<button class="link-button" data-type="${e(type)}" data-id="${e(id)}">${e(name)}</button>`;}
function table(head,rows,empty='No records yet.'){return rows.length?`<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th scope="col">${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<p class="empty">${e(empty)}</p>`;}
function panel(title,body,note=''){return `<section class="panel"><div class="panel-title"><h2>${e(title)}</h2>${note?`<p>${e(note)}</p>`:''}</div>${body}</section>`;}
function fields(values){return `<dl>${Object.entries(values).map(([k,v])=>`<dt>${e(k)}</dt><dd>${e(Array.isArray(v)?v.join(', '):v??'Unknown')}</dd>`).join('')}</dl>`;}
function matched(item){return !filter||[item.id,item.name,item.state,item.status,item.model].some(v=>String(v??'').toLowerCase().includes(filter.toLowerCase()));}
function agentTable(agents){return table(['Agent','Desired state','Container health','Gateway','Buzz','Active tasks'],agents.map(a=>[details('agent',a.id,a.name)+`<span class="secondary">${e(a.model)}</span>`,badge(a.state),badge(a.container.health),badge(gatewayState(a)),badge(a.gateway.buzz),e(a.gateway.active_tasks??'Unknown')]));}
function serviceTable(services){return table(['Service','Container','Health','CPU','Memory','Restarts'],services.map(s=>[details('service',s.id,s.id),badge(s.status),badge(s.health),s.cpu_percent==null?'Unknown':e(s.cpu_percent+'%'),e(bytes(s.memory_bytes)),e(s.restart_count)]));}
function operationTable(ops){return table(['Time (local)','Operation','Target','Outcome'],ops.map(o=>[e(o.updated_at!=null||o.created_at!=null?date(o.updated_at??o.created_at):'Not recorded'),e(label(o.action)),e(o.target),badge(o.state)]));}
function overview(){const unhealthy=data.agents.filter(a=>a.state==='running'&&(gatewayState(a)!=='responsive'||a.gateway.buzz!=='connected'));const badServices=data.services.filter(s=>s.status!=='completed'&&(s.status!=='running'||s.health!=='healthy'));const ready=data.agents.filter(a=>gatewayState(a)==='responsive'&&a.gateway.buzz==='connected').length;const active=data.agents.reduce((sum,a)=>sum+(a.gateway.active_tasks??0),0);const unknown=data.agents.some(a=>a.gateway.active_tasks==null);const cards=[['Agents connected',`${ready} / ${data.agents.length}`,'Responsive gateway and Buzz connection'],['Services healthy',`${data.services.filter(s=>s.health==='healthy'||s.status==='completed').length} / ${data.services.length}`,'Includes completed initialization jobs'],['Active tasks',`${active}${unknown?' + ?':''}`,unknown?'Some agent activity is unknown':'Reported by agent gateways'],['Needs attention',String(unhealthy.length+badServices.length),'Components with degraded or unknown health']];let html=`<div class="cards">${cards.map(([h,n,p])=>`<section class="card"><h3>${e(h)}</h3><div class="number">${e(n)}</div><p>${e(p)}</p></section>`).join('')}</div>`;if(unhealthy.length||badServices.length){html+=panel('Needs attention',`<div class="list">${unhealthy.map(a=>`<div class="list-row"><div>${details('agent',a.id,a.name)}<p>Gateway: ${e(gatewayState(a))} · Buzz: ${e(a.gateway.buzz)}</p></div>${badge(gatewayState(a))}</div>`).join('')}${badServices.map(s=>`<div class="list-row"><div>${details('service',s.id,s.id)}<p>Container: ${e(s.status)}</p></div>${badge(s.health)}</div>`).join('')}</div>`,'Open agent details to restart; service recovery stays in Compose');}html+=panel('Team',agentTable(data.agents));html+=`<div class="grid-two">${panel('Services',table(['Component','State'],data.services.map(s=>[details('service',s.id,s.id),badge(s.status==='completed'?'completed':s.health)])))}${panel('Recent operations',operationTable((data.activity.operations||[]).slice(0,5)))}</div>`;return html;}
function community(){const channels=data.channels.filter(matched);const projects=data.projects.filter(matched);const roster=data.community?.membership;return panel('Community members',table(['Public key','Role'],(roster?.members||[]).map(m=>[e(m.pubkey),e(m.role)]),roster?.status==='available'?'No community members.':'Community membership verification unavailable.'),'Authoritative Buzz roster')+panel('Channels',table(['Channel','Visibility','Registry','Buzz verification','Members'],channels.map(c=>[details('channel',c.id,c.name),e(c.visibility),badge(c.state),badge(c.buzz.status),c.buzz.status==='present'?e(c.buzz.members.length):'Unknown'])))+panel('Projects',table(['Project','Home channel','Registry','Buzz verification','Repositories'],projects.map(p=>[details('project',p.id,p.name),e(p.channel),badge(p.state),badge(p.buzz.status),e((p.repositories||[]).length)])))+panel('Repository announcements',table(['Repository','GitHub URL','Coordinate'],data.repositories.filter(matched).map(r=>[e(r.name||r.id),e(r.url),e(r.coordinate)])));}
function activity(){const ops=(data.activity.operations||[]).filter(o=>!filter||[o.action,o.target,o.state].some(v=>String(v??'').toLowerCase().includes(filter.toLowerCase())));const proposals=(data.activity.proposals||[]).filter(p=>!filter||JSON.stringify([p.id,p.actions,p.status]).toLowerCase().includes(filter.toLowerCase()));const messages=data.agents.flatMap(a=>(a.activity.messages||[]).map(m=>({...m,agent:a.name,agentId:a.id}))).sort((a,b)=>(b.timestamp||0)-(a.timestamp||0));return panel('Deployment operations',deploymentOperations(data.deployments?.operations||[]),'Host application lifecycle')+panel('Management operations',operationTable(ops),'Latest update first · '+localTimezone)+`<p class="muted small table-note">${e(data.activity.note||'')}</p>`+panel('COA proposals',table(['Created','Proposal','Actions','Status'],proposals.map(p=>[e(date(p.created_at)),e(short(p.id)),e(p.actions.map(label).join(', ')),e(label(p.status))])))+panel('Agent activity',table(['Time','Agent','Message type','Tool'],messages.filter(m=>!filter||[m.agent,m.role,m.tool].some(v=>String(v??'').toLowerCase().includes(filter.toLowerCase()))).slice(0,100).map(m=>[e(date(m.timestamp)),details('agent',m.agentId,m.agent),e(m.role),e(m.tool||'—')])),'Metadata only');}
function render(){if(!data)return;const titles={overview:['Community overview','Health, connections, and the work happening now.'],agents:['Agents','Runtime health, ownership, and recent activity.'],services:['Services','The infrastructure behind your community.'],community:['Community','Channels, projects, and repository announcements.'],deployments:['Deployments','Production services, immutable releases, and operation history.'],activity:['Activity','Management outcomes and agent activity metadata.']};if(!titles[view])view='overview';$('page-title').textContent=titles[view][0];$('subtitle').textContent=titles[view][1];$('breadcrumb').textContent='MISSION CONTROL / '+view.toUpperCase();$('community-name').textContent=data.community?.name||'Buzz community';document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const stale=data.stale||!data.collected_at||Date.now()/1000-data.collected_at>15;$('freshness').textContent=stale?'Observations stale':'Updated '+date(data.collected_at);let notes=[...(data.errors||[])];if(data.community&&!data.community.manager_ready)notes.push('Community setup or reconciliation is still pending.');if(stale)notes.unshift('Live observations are unavailable or delayed. Values below may be out of date.');$('notice').innerHTML=notes.length?`<div class="notice">${notes.map(e).join('<br>')}</div>`:'';let body=view==='overview'?overview():view==='agents'?panel('Managed agents',agentTable(data.agents.filter(matched))):view==='services'?panel('Community services',serviceTable(data.services.filter(matched))):view==='community'?community():view==='deployments'?deployments():activity();const previousFilter=$('filter');const focused=document.activeElement?.id==='filter';const selection=focused?document.activeElement.selectionStart:0;$('content').innerHTML=(view==='overview'?'':`<div class="toolbar"><input id="filter" type="search" aria-label="Filter records" placeholder="Filter by name, ID, or state…" value="${e(filter)}"><span>Owner access</span></div>`)+body;if(previousFilter&&$('filter')){$('filter').replaceWith(previousFilter);previousFilter.value=filter;}if(focused){$('filter').focus();$('filter').setSelectionRange(selection,selection);} }
async function request(path,options){const response=await fetch(API+path,{credentials:'same-origin',...options});if(response.status===401){showLogin();throw new Error('Owner sign-in required');}const result=await response.json();if(!response.ok)throw new Error(result.error||'Request unavailable');return result;}
function showLogin(){$('login').hidden=false;$('shell').hidden=true;$('detail').close();data=null;}
async function refresh(){if(fetching)return;fetching=true;$('refresh').disabled=true;try{data=await request('/overview');$('login').hidden=true;$('shell').hidden=false;render();}catch(error){if(data){data={...data,stale:true,errors:['Unable to refresh diagnostics. Showing the last available snapshot.']};render();}}finally{fetching=false;$('refresh').disabled=false;}}
async function showDetails(type,id){if(type==='deployment'){await deploymentDetails(id);return;}let item;let values={};let extra='';if(type==='agent'){item=data.agents.find(a=>a.id===id);if(!item)return;values={'Agent ID':item.id,'Public key':item.pubkey,'Owner (registry)':item.owner,'Desired state':item.state,'Container':item.container.status,'Container health':item.container.health,'Gateway':gatewayState(item),'Buzz connection':item.gateway.buzz,'Gateway state changed':date(item.gateway.updated_at),'Observed at':date(item.collected_at),'Buzz registration':item.registration?.status,'Active tasks':item.gateway.active_tasks,'Model':item.model,'Channels':item.channel_ids,'GitHub credential':item.github_credential||'Not assigned','Provider credential':data.community.provider_credential,'Instructions':item.instructions||'Managed COA instructions'};extra=panel('Recent activity',table(['Time','Role','Tool'],item.activity.messages.map(m=>[e(date(m.timestamp)),e(m.role),e(m.tool||'—')])));}else if(type==='service'){item=data.services.find(s=>s.id===id);if(!item)return;values={'Service':item.id,'Container':item.status,'Health':item.health,'Started':date(item.started_at),'Finished':date(item.finished_at),'Restarts':item.restart_count,'Exit code':item.exit_code,'OOM killed':item.oom_killed,'Image':item.image,'CPU':item.cpu_percent==null?'Unknown':item.cpu_percent+'%','Memory':bytes(item.memory_bytes),'Memory limit':bytes(item.memory_limit)};}else if(type==='channel'){item=data.channels.find(c=>c.id===id);if(!item)return;values={'Channel ID':item.id,'Buzz ID':item.uuid,'Visibility (registry)':item.visibility,'State (registry)':item.state,'Description':item.description,'Buzz verification':item.buzz.status,'Name (Buzz)':item.buzz.name,'Verified at':date(item.buzz.collected_at)};extra=panel('Authoritative Buzz membership',table(['Member public key','Role'],(item.buzz.members||[]).map(m=>[e(m.pubkey),e(m.role)]),item.buzz.status==='present'?'No members.':'Membership verification unavailable.'));}else{item=data.projects.find(p=>p.id===id);if(!item)return;values={'Project ID':item.id,'Coordinate':item.coordinate,'Description':item.description,'Channel (registry)':item.channel,'Visibility':item.visibility,'State (registry)':item.state,'Repositories (registry)':item.repositories,'Buzz verification':item.buzz.status,'Repositories (Buzz)':item.buzz.repositories,'Verified at':date(item.buzz.collected_at)};}
$('detail-type').textContent=type.toUpperCase()+(type==='agent'?' / OWNER ACCESS':' / READ ONLY');$('detail-title').textContent=item.name||item.id;$('detail-content').innerHTML=`<p class="muted small">Snapshot observed ${e(date(item.collected_at))}. Close and reopen for the latest details.</p><br>`+fields(values)+extra;if(type==='agent'){$('detail-content').insertAdjacentHTML('beforeend',`<section class="panel"><button data-config-agent="${e(id)}">Configure agent</button><h3>Restart agent</h3><p>Restarts the agent gateway while keeping its container and detached app servers running. Active agent work and attached terminal sessions may be interrupted.</p><button id="restart-agent" data-agent="${e(id)}" ${item.state!=='running'?'disabled':''}>Restart agent…</button><div id="restart-confirmation" hidden><p>Restart the gateway? Active agent work may be interrupted. Detached app servers keep running.</p><button id="confirm-restart">Confirm restart</button> <button id="cancel-restart">Cancel</button></div><p id="restart-result" role="status">${item.state!=='running'?'Restart is available only for agents with running desired state.':''}</p></section>`);}if(type==='agent'||type==='service'){const history=data.history.map(sample=>(type==='agent'?sample.agents:sample.services).find(x=>x.id===id)?.cpu_percent).slice(-60);$('detail-content').insertAdjacentHTML('beforeend',`<h3 class="section-label">CPU activity · latest samples</h3><div class="sparkline" aria-label="Recent CPU samples">${history.map(v=>`<i class="${v==null?'unknown':v<5?'low':v<50?'medium':'high'}" title="${e(v==null?'Unknown':v+'%')}"></i>`).join('')}</div><p class="small muted">Last hour maximum · history resets on manager restart.</p><h3 class="section-label">Sanitized diagnostic log</h3><div id="logs"><p class="muted">Loading diagnostic entries…</p></div>`);}if(!$('detail').open)$('detail').showModal();if(type==='agent'||type==='service'){try{const logs=await request('/logs?component='+encodeURIComponent(type==='agent'?'agent:'+id:id));if($('logs'))$('logs').innerHTML=`<p class="small muted">${e(logs.note)}</p><pre>${e(logs.entries.length?logs.entries.map(l=>`${l.timestamp?date(l.timestamp):'Time not recorded'} ${l.level.toUpperCase()} ${l.message}`).join('\n'):'No recognized diagnostics in the recent log window.')}</pre>`;}catch(error){if($('logs'))$('logs').textContent=error.message;}}}
$('login-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;$('login-error').textContent='';try{const response=await fetch(API+'/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:$('access-key').value})});const result=await response.json();if(!response.ok)throw new Error(result.error);$('access-key').value='';await refresh();}catch(error){$('login-error').textContent=error.message;}finally{button.disabled=false;}});
$('logout').addEventListener('click',async()=>{try{await request('/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});showLogin();}catch(error){$('notice').textContent='Sign-out failed. Retry when the dashboard is reachable.';}});
$('refresh').addEventListener('click',refresh);$('close-detail').addEventListener('click',()=>$('detail').close());$('content').addEventListener('click',event=>{const target=event.target.closest('[data-type]');if(target)showDetails(target.dataset.type,target.dataset.id);});$('content').addEventListener('input',event=>{if(event.target.id==='filter'){filter=event.target.value;render();}});window.addEventListener('hashchange',()=>{view=location.hash.slice(1)||'overview';filter='';render();});view=location.hash.slice(1)||'overview';document.querySelector('footer').textContent+=' All times are local ('+localTimezone+').';refresh();setInterval(()=>{if(!$('shell').hidden)refresh();},5000);

$('detail-content').addEventListener('click',async event=>{
  const target=event.target.closest('button');
  if(!target)return;
  if(target.id==='restart-agent'){$('restart-confirmation').hidden=false;target.disabled=true;$('confirm-restart').focus();return;}
  if(target.id==='cancel-restart'){$('restart-confirmation').hidden=true;$('restart-agent').disabled=false;$('restart-agent').focus();return;}
  if(target.id!=='confirm-restart')return;
  const button=$('restart-agent');
  const id=button.dataset.agent;
  $('restart-confirmation').hidden=true;
  button.disabled=true;
  const output=$('restart-result');
  output.textContent='Restarting gateway… The container stays running.';
  const random=crypto.getRandomValues(new Uint8Array(16));
  random[6]=(random[6]&15)|64;random[8]=(random[8]&63)|128;
  const hex=Array.from(random,b=>b.toString(16).padStart(2,'0')).join('');
  const requestId=[hex.slice(0,8),hex.slice(8,12),hex.slice(12,16),hex.slice(16,20),hex.slice(20)].join('-');
  try{
    const result=await request('/agents/'+encodeURIComponent(id)+'/restart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:requestId})});
    output.textContent=result.message+' Close details to monitor live health.';
    await refresh();
  }catch(error){output.textContent=error.message+' Check current health before retrying.';}
  finally{button.disabled=false;}
});

function deploymentOperations(ops){return table(['Updated','Application','Operation','Release','Outcome'],ops.map(j=>[e(date(j.updated_at)),details('deployment',j.application+'/'+j.environment,j.application+' / '+j.environment),e(label(j.action)),e(j.release),badge(j.state)]));}
function deployments(){const snap=data.deployments;if(!snap)return panel('Deployments','<p class="empty">Deployment observations unavailable.</p>');const apps=snap.applications.filter(a=>!filter||JSON.stringify([a.id,a.environment,a.repository,a.current]).toLowerCase().includes(filter.toLowerCase()));return (snap.stale?'<div class="notice">Deployment observations are stale. Last collected '+e(date(snap.collected_at))+'.</div>':'')+panel('Hosted applications',table(['Application','Environment','Release','Services','Published ports'],apps.map(a=>[details('deployment',a.id+'/'+a.environment,a.id),e(a.environment),e(a.current||'Not deployed'),a.services.map(s=>e(s.id)+' '+badge(s.health==='unknown'?s.status:s.health)).join('<br>'),a.services.filter(s=>s.host_port).map(s=>e(s.id+': '+s.host_port)).join('<br>')])),'Containers run on the hosting VM independently of agents.')+panel('Deployment operations',deploymentOperations(snap.operations.filter(j=>!filter||JSON.stringify([j.application,j.environment,j.release,j.state]).toLowerCase().includes(filter.toLowerCase()))),'Persistent history · all times '+localTimezone);}
async function deploymentDetails(id){const app=data.deployments?.applications.find(a=>a.id+'/'+a.environment===id);if(!app)return;$('detail-type').textContent='HOSTED APPLICATION / READ ONLY';$('detail-title').textContent=app.id+' / '+app.environment;const ops=data.deployments.operations.filter(j=>j.application===app.id&&j.environment===app.environment);$('detail-content').innerHTML=fields({'Repository':app.repository,'Current release':app.current||'Not deployed','Previous release':app.previous||'None','Observed at':date(data.deployments.collected_at)})+panel('Services',table(['Service','Container','Health','Restarts','Started','Port'],app.services.map(s=>[e(s.id),badge(s.status),badge(s.health),e(s.restart_count),e(date(s.started_at)),e(s.host_port||'Internal')])) )+panel('Operation history',ops.length?ops.map(j=>'<section><h3>'+e(label(j.action))+' · '+e(j.release)+' '+badge(j.state)+'</h3><p class="small muted">'+e(j.id)+'</p><pre>'+e(j.events.map(ev=>date(ev.timestamp)+'  '+ev.message).join('\n'))+'</pre></section>').join(''):'<p class="empty">No deployments have been requested.</p>')+'<h3>Service diagnostics</h3><p class="small muted">Bounded diagnostic summaries. Request payloads and raw command output are excluded.</p><div id="deployment-logs">Loading logs…</div>';if(!$('detail').open)$('detail').showModal();const entries=await Promise.all(app.services.map(async s=>{try{const result=await request('/deployments/logs?'+new URLSearchParams({application:app.id,environment:app.environment,service:s.id}));return '<h4>'+e(s.id)+'</h4><pre>'+e(result.entries.length?result.entries.map(l=>date(l.timestamp)+' '+l.level.toUpperCase()+' '+l.message).join('\n'):'No recognized diagnostics in the recent log window.')+'</pre>';}catch(err){return '<p>'+e(s.id)+': '+e(err.message)+'</p>';}}));if($('deployment-logs'))$('deployment-logs').innerHTML=entries.join('');}
