'use strict';
// Mission Control: environment profiles and secrets for one hosted application environment.
let pm=null,pmKey=null,pmRequest=0,pmRevealTimer=null;
$('detail').addEventListener('close',()=>{pmRequest++;pm=null;pmKey=null;clearTimeout(pmRevealTimer);});
const pmPost=body=>request('/deployments/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({application:pmKey[0],environment:pmKey[1],...body})});
const pmCount=(n,word)=>n+' '+word+(n===1?'':'s');
const pmSpec=p=>({id:p.id,values:p.values||{},secrets:p.secret_refs||{},files:p.file_refs||{},required_env:p.required_env||[],connections:p.connections||[]});
function pmStatus(message){const el=$('pm-status');if(el){el.textContent=message||'';el.hidden=!message;}}
function pmWork(html){$('pm-work').innerHTML=html;const first=$('pm-work').querySelector('input,textarea,button');if(first)first.focus();}
function pmNextId(id){const ids=pm.profiles.map(p=>p.id);const m=/^(.*-v)(\d+)$/.exec(id);if(!m){let n=2;while(ids.includes(id+'-v'+n))n++;return id+'-v'+n;}let n=Math.max(...ids.map(x=>{const k=new RegExp('^'+m[1].replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(\\d+)$').exec(x);return k?Number(k[1]):0;}))+1;return m[1]+n;}
async function openProfiles(key,message){const current=++pmRequest;pmKey=key.split('/');$('detail-type').textContent='HOSTED APPLICATION / PROFILES AND SECRETS';$('detail-title').textContent=pmKey[0]+' / '+pmKey[1];if(!pm)$('detail-content').innerHTML='<p>Loading profiles…</p>';try{const record=await request('/deployments/manage?'+new URLSearchParams({application:pmKey[0],environment:pmKey[1]}));if(current!==pmRequest)return;pm=record;renderProfiles();pmStatus(message);}catch(error){if(current===pmRequest)$('detail-content').innerHTML=`<p class="notice">${e(error.message)}</p>`;}}
function renderProfiles(){const r=pm,pol=r.policy;const tag=(text,cls)=>`<span class="badge ${cls}">${e(text)}</span>`;
const rows=r.profiles.map(p=>[`<strong>${e(p.id)}</strong> ${p.id===r.active?tag('deployed','good'):''} ${pol&&p.id===pol.profile?tag('used for releases','good'):''}`,e(pmCount(Object.keys(p.values||{}).length,'value')),e(pmCount(Object.keys(p.secret_refs||{}).length,'secret')+', '+pmCount(Object.keys(p.file_refs||{}).length,'file')),e(pmCount((p.connection_checks||[]).length,'check')),`<div class="pm-actions"><button data-pm="view" data-profile="${e(p.id)}">View</button><button data-pm="copy" data-profile="${e(p.id)}">Copy &amp; edit</button><button data-pm="preflight" data-profile="${e(p.id)}">Preflight</button><button data-pm="use" data-profile="${e(p.id)}" ${!pol||p.id===pol.profile?'disabled':''} title="${pol?'Use this profile for automatic releases':'No release policy configured'}">Use for releases</button><button data-pm="redeploy" data-profile="${e(p.id)}" ${r.current?'':'disabled'} title="Redeploy ${e(r.current||'')} with this profile">Redeploy</button></div>`]);
const secrets=r.credentials.map(c=>[`<strong>${e(c.id)}</strong>`,c.version?e(short(c.version)):badge('missing'),e(c.updated_at?date(c.updated_at):'—'),e(c.used_by.join(', ')||'Not referenced'),`<div class="pm-actions"><button data-pm="secret" data-id="${e(c.id)}" data-exists="${c.version?1:''}">${c.version?'Replace':'Store'}</button><button data-pm="generate" data-id="${e(c.id)}" data-exists="${c.version?1:''}">${c.version?'Regenerate':'Generate'}</button><button data-pm="reveal" data-id="${e(c.id)}" ${c.version?'':'disabled'}>Reveal</button></div>`]);
$('detail-content').innerHTML=`<p id="pm-status" class="notice" role="status" hidden></p>`+fields({'Deployed release':r.current||'Not deployed','Deployed with profile':r.active||'None','Release policy':pol?(pol.enabled?'Enabled':'Disabled')+' · uses '+pol.profile:'Not configured','Last preflight':r.preflight?(r.preflight.ready?'Passed':'Failed')+' · '+(r.preflight.profile||'')+' · '+date(r.preflight.checked_at):'Not run'})
+`<p class="small muted">Profiles cannot be changed: “Copy &amp; edit” saves a new profile ID. Switching the release profile affects the next automatic release; “Redeploy” applies a profile to the current release now. Secret changes take effect on the next deployment.</p>`
+panel('Environment profiles',table(['Profile','Settings','References','Connection checks','Actions'],rows,'No profiles registered yet.'))
+`<div id="pm-work"></div>`
+panel('Secrets',table(['Name','Version','Changed','Used by','Actions'],secrets,'No secrets stored.')+`<button data-pm="secret" data-id="" data-exists="">Add a secret…</button>`,'Values are never shown unless you reveal one with the access key')
+panel('Change log',table(['Time','Action','Target','Outcome'],(r.audit||[]).map(a=>[e(date(a.time)),e(label(a.action)),e(a.id||a.profile||'—'),badge(a.outcome==='done'?'succeeded':'failed')]),'No changes from Mission Control yet.'),'Recorded without secret values');}
function pmView(id){const p=pm.profiles.find(x=>x.id===id);const v=Object.entries(p.values||{}).map(([k,x])=>[e(k),e(x)]);const s=Object.entries(p.secret_refs||{}).map(([k,x])=>[e(k),e('secret: '+x)]);const f=Object.entries(p.file_refs||{}).map(([k,x])=>[e(k),e('file: '+x)]);pmWork(panel('Profile '+id,table(['Variable or file','Value or reference'],[...v,...s,...f],'Empty profile.')+fields({'Required variables':p.required_env||[],'Connection checks':(p.connections||[]).map(c=>c.id+' → '+c.host+':'+c.port)})+`<button data-pm="close-work">Close</button>`));}
function pmCopy(id){const p=pm.profiles.find(x=>x.id===id);const spec=pmSpec(p);spec.id=pmNextId(id);pmWork(panel('New profile from '+id,`<form id="pm-profile-form" class="pm-form"><p class="small muted">Edit the JSON and save. The new ID must not exist yet. Secrets are referenced by name; store their values under Secrets.</p><label for="pm-profile-json">Profile</label><textarea id="pm-profile-json" rows="18" spellcheck="false">${e(JSON.stringify(spec,null,2))}</textarea><div class="pm-actions"><button type="submit">Save as new profile</button><button type="button" data-pm="close-work">Cancel</button></div></form>`));}
function pmSecret(id,exists){pmWork(panel(id?(exists?'Replace secret '+id:'Store secret '+id):'Add a secret',`<form id="pm-secret-form" class="pm-form" data-exists="${exists?1:''}"><label for="pm-secret-id">Name</label><input id="pm-secret-id" value="${e(id)}" ${id?'readonly':''} required pattern="[a-z][a-z0-9-]{0,47}" autocomplete="off"><label for="pm-secret-value">Value</label><textarea id="pm-secret-value" rows="4" spellcheck="false" autocomplete="off"></textarea><label for="pm-secret-file">…or upload a file (e.g. users.yaml)</label><input id="pm-secret-file" type="file"><p class="small muted">${exists?'The current value is replaced. The application keeps the old value until its next deployment.':'Stored values are never shown again unless revealed with the access key.'}</p><div class="pm-actions"><button type="submit">${exists?'Replace':'Store'}</button><button type="button" data-pm="close-work">Cancel</button></div></form>`));}
function pmReveal(id){pmWork(panel('Reveal '+id,`<form id="pm-reveal-form" class="pm-form" data-id="${e(id)}"><p class="small muted">Re-enter the Mission Control access key. The reveal is recorded in the change log. The value hides after 60 seconds.</p><label for="pm-reveal-key">Access key</label><input id="pm-reveal-key" type="password" required autocomplete="current-password"><div class="pm-actions"><button type="submit">Reveal</button><button type="button" data-pm="close-work">Cancel</button></div></form><div id="pm-reveal-output"></div>`));}
async function pmRun(button,action,body,success){button.disabled=true;try{const result=await pmPost({action,...body});await openProfiles(pmKey.join('/'),success(result));}catch(error){pmStatus(error.message);button.disabled=false;}}
$('detail-content').addEventListener('click',async event=>{const open=event.target.closest('[data-manage-profiles]');if(open){pm=null;await openProfiles(open.dataset.manageProfiles);return;}const b=event.target.closest('[data-pm]');if(!b||!pm)return;const action=b.dataset.pm,profile=b.dataset.profile,id=b.dataset.id;pmStatus('');
if(action==='close-work'){clearTimeout(pmRevealTimer);pmWork('');return;}
if(action==='view')return pmView(profile);if(action==='copy')return pmCopy(profile);if(action==='secret')return pmSecret(id,!!b.dataset.exists);if(action==='reveal')return pmReveal(id);
if(action==='hide-secret'){clearTimeout(pmRevealTimer);$('pm-reveal-output').replaceChildren();return;}
if(action==='preflight'){b.disabled=true;try{const r=await pmPost({action:'preflight',profile});pmWork(panel('Preflight · '+profile,`<p>${r.ready?badge('succeeded')+' Ready to deploy':badge('failed')+' Not ready'}</p>`+table(['Check','Type','Result'],(r.checks||[]).map(c=>[e(c.id),e(c.kind),badge(c.status)]))+`<button data-pm="close-work">Close</button>`));}catch(error){pmStatus(error.message);}finally{b.disabled=false;}return;}
if(action==='use'){if(!confirm(`Use profile ${profile} for automatic releases of ${pmKey[0]} / ${pmKey[1]}? The next automatic release uses it.`))return;return pmRun(b,'policy-profile',{profile,expected_version:pm.policy.version},()=>`Automatic releases now use ${profile}.`);}
if(action==='redeploy'){if(!confirm(`Redeploy ${pm.current} to ${pmKey[1]} with profile ${profile} now? Services restart briefly.`))return;return pmRun(b,'redeploy',{profile},r=>`Deployment queued (${short(r.job)}). Follow it under Deployment operations.`);}
if(action==='generate'){if(!confirm(b.dataset.exists?`Replace ${id} with a new random token? Anything else using the old value stops working after the next deployment.`:`Generate a random token for ${id}?`))return;return pmRun(b,'credential',{id,generate:true,rotate:!!b.dataset.exists},()=>`${id} ${b.dataset.exists?'regenerated':'generated'}. It takes effect on the next deployment.`);}});
$('detail-content').addEventListener('submit',async event=>{const form=event.target;if(!pm||!['pm-profile-form','pm-secret-form','pm-reveal-form'].includes(form.id))return;event.preventDefault();const button=form.querySelector('[type=submit]');pmStatus('');
if(form.id==='pm-profile-form'){let profile;try{profile=JSON.parse($('pm-profile-json').value);}catch{pmStatus('The profile is not valid JSON.');return;}return pmRun(button,'profile',{profile},r=>`Profile ${r.id} saved. Run preflight, then use it for releases or redeploy.`);}
if(form.id==='pm-secret-form'){const id=$('pm-secret-id').value.trim();const file=$('pm-secret-file').files[0];const value=file?await file.text():$('pm-secret-value').value;if(!value){pmStatus('Enter a value or choose a file.');return;}const exists=!!form.dataset.exists||pm.credentials.some(c=>c.id===id&&c.version);return pmRun(button,'credential',{id,value,rotate:exists},()=>`${id} ${exists?'replaced':'stored'}. It takes effect on the next deployment.`);}
const id=form.dataset.id;button.disabled=true;try{const r=await pmPost({action:'reveal',id,key:$('pm-reveal-key').value});$('pm-reveal-key').value='';const out=$('pm-reveal-output');out.innerHTML=`<pre class="pm-secret"></pre><button data-pm="hide-secret">Hide</button>`;out.querySelector('pre').textContent=r.value;clearTimeout(pmRevealTimer);pmRevealTimer=setTimeout(()=>{if($('pm-reveal-output'))$('pm-reveal-output').replaceChildren();},60000);}catch(error){pmStatus(error.message);}finally{button.disabled=false;}});
